### ISSUE TITLE
Invalid model because of lookup in partial class

### ISSUE THREAD

**Issue by casella** [lbl-srg/modelica-buildings#2229]
Please check [Buildings.Fluid.HeatExchangers.DXCoils.BaseClasses.Examples.NominalCondition](https://libraries.openmodelica.org/branches/newInst/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.Fluid.HeatExchangers.DXCoils.BaseClasses.Examples.NominalCondition.err). OpenModelica reports that
```
[Buildings 7.0.0/Fluid/HeatExchangers/DXCoils/BaseClasses/NominalCondition.mo:36:3-40:32:writable] 
Error: Medium is partial, name lookup is not allowed in partial classes.
```
The package `Medium` is declared to be a replaceable partial class, but is not subsequently redeclared to a non-partial one before being used. This is forbidden by the [Modelica Specification, Section 5.3.2](https://specification.modelica.org/v3.4/Ch5.html#composite-name-lookup): "The class we look inside may not be partial in a simulation model".

**Comment by mwetter** [comment]
Correct, a non-partial media need to be assigned.

**Comment by casella** [comment]
When you fix this, can you pls. back-port it to a 7.0.1 maintenance branch, so we can refer to that for our work?

**Comment by mwetter** [comment]
Would a 7.0.1 branch be helpful for you, otherwise we would not likely do one but rather focus on getting 8.0.0 out, which has already a lot of fixes.

**Comment by mwetter** [comment]
@casella : I think we have a bigger problem: Consider
```modelica
class Cl

  model A
    B myB(redeclare package Medium = Modelica.Media.Air.MoistAir);
  end A;
  
  model B
    replaceable package Medium = Modelica.Media.Interfaces.PartialMedium;
    
    // The statement below is not valid, and leads to an error in checking the model B in OMEdit.
    parameter Modelica.SIunits.SpecificEnthalpy h_default = Medium.specificEnthalpy_pTX(
      p=Medium.p_default,
      T=Medium.T_default,
      X=Medium.X_default) "Default enthalpy for the selected medium";
  end B;
  
end Cl;
```
which fails the model check for `B` in OMEdit. Also, `Modelica.Fluid.Vessels.ClosedVolume` fails to check, as does `Pipes.StaticPipe`, `Valves.ValveLinear` and probably many others in the MSL.

The above pattern is used throughout `Modelica.Fluid`.

**Comment by casella** [comment]
> 
> 
> Would a 7.0.1 branch be helpful for you, otherwise we would not likely do one but rather focus on getting 8.0.0 out, which has already a lot of fixes.

See email

**Comment by casella** [comment]
> 
> 
> @casella : I think we have a bigger problem: Consider
> 
> ```modelica
> class Cl
> 
>   model A
>     B myB(redeclare package Medium = Modelica.Media.Air.MoistAir);
>   end A;
>   
>   model B
>     replaceable package Medium = Modelica.Media.Interfaces.PartialMedium;
>     
>     // The statement below is not valid, and leads to an error in checking the model B in OMEdit.
>     parameter Modelica.SIunits.SpecificEnthalpy h_default = Medium.specificEnthalpy_pTX(
>       p=Medium.p_default,
>       T=Medium.T_default,
>       X=Medium.X_default) "Default enthalpy for the selected medium";
>   end B;
>   
> end Cl;
> ```
> 
> which fails the model check for `B` in OMEdit. Also, `Modelica.Fluid.Vessels.ClosedVolume` fails to check, as does `Pipes.StaticPipe`, `Valves.ValveLinear` and probably many others in the MSL.
> 
> The above pattern is used throughout `Modelica.Fluid`.

That is a problem with the 'Check' feature, which tries to instantiate the model, and of course it can't because it still refers to partial models. We should introduce some relaxations so that instantiation of partial stuff proceeds, see [#6217](https://trac.openmodelica.org/OpenModelica/ticket/6217).

Then, we should also report that the model is locally balanced, despite some equations potentially being missing from the partial class. This is covered by [#3977](https://trac.openmodelica.org/OpenModelica/ticket/3977), which is not currently our highest priority.

**Comment by mwetter** [comment]
@casella : In view of https://trac.openmodelica.org/OpenModelica/ticket/6217, I assume this won't need to be fixed in the Buildings library for the `maint_7.0.x` branch, correct?

**Comment by casella** [comment]
@mwetter, it will still need to be fixed. 

- When you _check_ a model (e.g. a standalone component in a library) it is OK to have missing parameters and/or unredeclared partial classes. The model is not invalid, it is incomplete, but that's expected in a library.
- When you _compile_ a model to _simulate_ it, everything should be in place, including parameter values and non-partial redeclared classes. In particular, as I wrote in the first comment, the Modelica specification requires that "The class we look inside may not be partial in a _simulation_ model".

**Comment by mwetter** [comment]
@casella : I am not sure we talk about the same: Once https://trac.openmodelica.org/OpenModelica/ticket/6217 is fixed, then models like the example `Cl` will work, and hence also `Buildings 7.0.0/Fluid/HeatExchangers/DXCoils/BaseClasses/NominalCondition.mo` should work, as will the models in `Modelica.Fluid`, which currently (almost all?) fail to check with OMEdit.

Hence, I think keeping models with the pattern as in the example `Cl` is fine. If not, 100's of models will need to be changed, and the whole design principle of `.Fluid` in which a user *has* to redeclare the medium prior to simulation won't work.

Consequently, I would think we don't need to apply this patch to the `maint_7.0.x` branch. If you prefer to apply the patch so other tests can proceed, I'd be happy to do so.

**Comment by casella** [comment]
> @casella : I am not sure we talk about the same

Neither am I 😄 

> Once https://trac.openmodelica.org/OpenModelica/ticket/6217 is fixed, then models like the example `Cl` will work

That depends on your definition of _work_.

`Cl` is a technically a model, but it only contains class definitions; there are no components, variables, or equations in it. As such, it is valid and can be legally compiled it into a simulation executable, but it does not compute anything, so it is rather useless as such. In fact, you can both check and compile `Cl` successfully with today's OMC, and what you'll get out of this is nothing, as expected.

I guess it makes more sense to consider `Cl` as a package instead, and then check and compile its models `Cl.A` and `Cl.B`.
- `Cl.A` is a valid simulation model, because there are no partial classes in it. As such, it can be both checked and simulated successfully with today's OMC
- `Cl.B` is a valid model, so it should check successfully, and it will once we fix [#6217](https://trac.openmodelica.org/OpenModelica/ticket/6217). However, it is not a valid _simulation_ model, because it calls a function from a partial package, so it lacks some information to be fully defined and, according to Sect. 5.3.2. of the spec, cannot be compiled into simulation code. Indeed, OMC correctly complains that "[Cl: 11:5-14:69]: Medium is partial, name lookup is not allowed in partial classes.". As such, it cannot be compiled.

Component models in the Modelica.Fluid library are like `Cl.B`, so they can't be simulated as such, but they need their partial medium model to be redeclared.

That said, my original diagnostic on `Buildings.Fluid.HeatExchangers.DXCoils.BaseClasses.Examples.NominalCondition` was wrong, my fault. That model declares a parameter `nomCon` of type `Buildings.Fluid.HeatExchangers.DXCoils.BaseClasses.NominalCondition`, but indeed it [redeclares the partial medium package](https://github.com/lbl-srg/modelica-buildings/blob/1c33517c61d57fd8bbda7a5265f0fe0a66f817b0/Buildings/Fluid/HeatExchangers/DXCoils/BaseClasses/Examples/NominalCondition.mo#L6), so I guess there is something wrong with OMC that does not recognize this.

I opened [#6221](https://trac.openmodelica.org/OpenModelica/ticket/6221) to address this issue.

**Comment by mwetter** [comment]
@casella : Great, now we both agree. In this case I will leave `maint_7.0.x` as is.

**Comment by casella** [comment]
Yep. Maybe it could still get useful later, when we compare the results.

**Comment by casella** [comment]
@mwetter I question the label "OpenModelica" here. This issue was because of code which is not compilant to the Modelica Specification. You can't blame OpenModelica because it follows the rules 😃
